analytics: {}
color:
  brandColors:
    - '#E0E0D0'
    - '#000000'
    - '#708088'
    - '#000000'
    - '#000000'
  brandStrength: 0.318693
  lightness: 0.933901
  rhythmicContrast: 0.680528
  saturation: 0.753378
cta: {}
layout_spectrum: 0.417792
name: Koskars
opengraph: {}
purpose: []
typography_spectrum: 0.229729
