analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.318693
  lightness: 0.933901
  rhythmicContrast: 0.680528
  saturation: 0.173075
cta: {}
layout_spectrum: 0.638513
name: Koskars
opengraph: {}
purpose: []
typography_spectrum: 0.7188385566696525
