analytics: {}
color:
  brandColors:
    - '#E0E0D0'
    - '#000000'
    - '#708088'
    - '#000000'
    - '#000000'
  brandStrength: 0.318693
  lightness: 0.75
  rhythmicContrast: 0.75
  saturation: 0.362771
cta: {}
layout_spectrum: 0.77089
name: Koskars
opengraph: {}
purpose: []
typography_spectrum: 0.229729
